// This file was generated by Mendix Modeler 7.15.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package autologin.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the AutoLogin module

	/**
	* The number of seconds in which the token is valid for newly created login tokens
	*/
	public static java.lang.Long getLOGIN_TOKEN_VALIDITY()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("AutoLogin.LOGIN_TOKEN_VALIDITY");
	}
}